version: '3'

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: -config.file=/etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./prometheus:/etc/prometheus/