version: '3.4'

services:

  drupal:
    image: drupal
    ports:
      - '80:80'
    volumes:
      - module_volume:/var/www/html/modules
      - profile_volume:/var/www/html/profiles
      - site_volume:/var/www/html/sites
      - theme_volume:/var/www/html/themes
  db:
    image: postgres
    environment:
      - POSTGRES_USER=akilan
      - POSTGRES_PASSWORD=akilan@123
    volumes:
      - db_volume:/var/lib/postgresql/data
  
volumes:
  module_volume:
  profile_volume:
  site_volume:
  theme_volume:
  db_volume:


