# Run "docker-compose -f apache-compose.yaml up --build"

version: '3.4'

services:  #Grouping Containers as a Service
  
  #php container creation

  web:
    build: .
    image: akilan/php-employee:1
    ports:
      - '80:80'
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PWD=akilan@123
      - DB_NAME=employee

  #Mysql container creation

  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: akilan/mysql-employee:1
    environment:
      - MYSQL_ROOT_PASSWORD=akilan@123 # setting DB password
    volumes:
      - db_volume:/var/lib/mysql # store DB data in volume

volumes:
  
  db_volume:
  
