vesrion: '3.4'

services:

  php-app:
    image: akilan/php-employee:1
    ports:
      - '80:80'
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PWD=run/secrets/mysql-pwd
      - DB_NAME=employee
    secrets:
      - mysql-pwd

  mysql-db:
    image: akilan/mysql-employee:1
    secrets:
      - mysql-pwd
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=run/secrets/mysql-pwd # setting DB password
    volumes:
      - db_volume:/var/lib/mysql # store DB data in volume

volumes:
  
  db_volume:

secrets:

  mysql-pwd:
    external: true